import json
from datetime import date
import anthropic
from rich.console import Console
from rich.panel import Panel
from config import ANTHROPIC_API_KEY, CLAUDE_MODEL, USER_NAME
from storage.db import get_all_standups

console = Console()
client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)


def _collect_all_data(standups: list) -> dict:
    all_wins = []
    all_tags = []
    weekly_entries = {}

    for s in standups:
        week = _week_label(s["date"])
        if week not in weekly_entries:
            weekly_entries[week] = []
        weekly_entries[week].append(s)

        try:
            wins = json.loads(s["wins"]) if s["wins"] else []
            all_wins.extend(wins)
        except (json.JSONDecodeError, TypeError):
            pass

        try:
            tags = json.loads(s["tags"]) if s["tags"] else []
            all_tags.extend(tags)
        except (json.JSONDecodeError, TypeError):
            pass

    return {
        "weekly_entries": weekly_entries,
        "all_wins": all_wins,
        "top_tags": _top_tags(all_tags),
    }


def _week_label(date_str: str) -> str:
    from datetime import datetime, timedelta
    d = datetime.strptime(date_str, "%Y-%m-%d").date()
    monday = d - timedelta(days=d.weekday())
    sunday = monday + timedelta(days=6)
    return f"{monday.strftime('%b %d')} – {sunday.strftime('%b %d, %Y')}"


def _top_tags(tags: list) -> list:
    counts = {}
    for t in tags:
        counts[t] = counts.get(t, 0) + 1
    return sorted(counts, key=counts.get, reverse=True)[:10]


def _generate_executive_summary(standups: list) -> str:
    entries_text = ""
    for s in standups[-20:]:  # last 20 standups for context
        entries_text += f"\n- {s['date']}: {s.get('yesterday', '')}"

    prompt = f"""
You are writing a performance review self-assessment for a software engineer named {USER_NAME}.

Based on their recent standup logs, write a 3-4 sentence executive summary of their impact and contributions.
Use strong, active language. Focus on outcomes and impact, not just tasks.
Write in first person ("I built...", "I led...", "I shipped...").

Standup log:
{entries_text}

Return only the summary text, no headers or extra formatting.
"""
    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.content[0].text.strip()


def _render_markdown(data: dict, summary: str, standups: list) -> str:
    today = str(date.today())
    date_range = f"{standups[-1]['date']} to {standups[0]['date']}" if standups else today

    lines = []
    lines.append(f"# ImpactLog — Performance Summary")
    lines.append(f"**Period:** {date_range}  ")
    lines.append(f"**Generated:** {today}  ")
    lines.append(f"**Engineer:** {USER_NAME}\n")

    lines.append("---\n")

    lines.append("## Executive Summary\n")
    lines.append(summary + "\n")

    lines.append("---\n")

    lines.append("## Skills & Technologies\n")
    lines.append(", ".join(f"`{t}`" for t in data["top_tags"]) or "_None tagged yet_")
    lines.append("\n")

    lines.append("---\n")

    lines.append("## Weekly Breakdown\n")
    for week, entries in data["weekly_entries"].items():
        lines.append(f"### Week of {week}\n")
        for s in entries:
            try:
                wins = json.loads(s["wins"]) if s["wins"] else []
            except (json.JSONDecodeError, TypeError):
                wins = []

            lines.append(f"**{s['date']}**")
            if wins:
                for w in wins:
                    lines.append(f"- {w}")
            else:
                lines.append(f"- {s.get('yesterday', '_No entry_')}")
            if s.get("blockers") and s["blockers"] != "None":
                lines.append(f"  - _Blocker: {s['blockers']}_")
            lines.append("")

    lines.append("---\n")
    lines.append("_Generated by [ImpactLog](https://github.com/DolasPooja99/ImpactLog)_\n")

    return "\n".join(lines)


def export_markdown():
    standups = get_all_standups()

    if not standups:
        console.print(Panel("[yellow]No standups logged yet. Nothing to export.[/yellow]", expand=False))
        return

    console.print(f"\n[yellow]Building your perf doc from {len(standups)} standup(s)...[/yellow]")

    data = _collect_all_data(standups)

    console.print("[yellow]Writing executive summary with Claude...[/yellow]")
    summary = _generate_executive_summary(standups)

    markdown = _render_markdown(data, summary, standups)

    filename = f"impactlog_export_{date.today()}.md"
    with open(filename, "w") as f:
        f.write(markdown)

    console.print(Panel(
        f"[bold green]Export saved![/bold green]\n\n"
        f"File: [bold]{filename}[/bold]\n"
        f"Entries: {len(standups)} standups\n"
        f"Top skills: {', '.join(data['top_tags'][:5]) or 'none yet'}\n\n"
        f"[dim]Open the file and paste it into your perf doc, Notion, or Google Doc.[/dim]",
        title="Markdown Export",
        expand=False
    ))
